on:
  push:
    paths:
      - '**.py'
      - '.github/**'

  pull_request:
    paths:
      - '**.py'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11-dev']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          pip install -U pip wheel
          pip install -r .github/pythonchecks.txt
      - name: Build Package Version
        run: |
          pip uninstall requests filelock -y
          sudo apt-get install -y python3-requests python3-filelock
          sudo apt-get install -y apt python3-apt apt-file dpkg-dev fakeroot build-essential devscripts debhelper
          sudo apt-file update
          pip install build wheel2deb
          cd modules/mediawiki/files/bin
          pyproject-build --wheel --outdir dist .
          cd dist
          pip wheel MW_SRE_Utils-3.0-py3-none-any.whl
          wheel2deb
          wheel2deb build
          ls -l output/*.deb
          dpkg -i output/*.deb


