on:
  push:
    paths:
      - '**.py'
      - '.github/**'

  pull_request:
    paths:
      - '**.py'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11-dev']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          pip install -U pip wheel
          pip install -r .github/pythonchecks.txt
      - name: Run tests
        run: |
          mypy modules/mediawiki modules/ssl modules/monitoring --ignore-missing-imports
          coverage run --branch -m pytest modules/mediawiki
          coverage report --fail-under=70
          vermin -v --eval-annotations --backport argparse --backport importlib --backport ipaddress --backport typing --backport dataclasses --no-parse-comments .
      - name: Build Package Version
        run: |
          pip uninstall requests filelock -y
          sudo apt-get install -y python3-requests python3-filelock
          pip install build wheel2deb
          pyproject-build --wheel --outdir dist .
          cd dist
          pip wheel MW_SRE_Utils-3.0-py3-none-any.whl
          wheel2deb
          wheel2deb build
          ls -l output/*.deb
          dpkg -i output/*.deb


